import { ROLES } from './roles.constants';

export const ENDPOINTS = {
  AUTH: {
    REGISTER: 'POST /api/v1/auth/register',
    LOGIN: 'POST /api/v1/auth/login',
    REFRESH: 'POST /api/v1/auth/refresh',
    LOGOUT: 'POST /api/v1/auth/logout',
  },
  EVENTS: {
    CREATE: 'POST /api/v1/events',
    LIST: 'GET /api/v1/events',
    DETAIL: 'GET /api/v1/events/:id',
  },
  REWARDS: {
    CREATE: 'POST /api/v1/rewards',
    DETAIL: 'GET /api/v1/rewards/:id',
  },
  REWARD_REQUESTS: {
    CREATE: 'POST /api/v1/reward-requests',
    DETAIL: 'GET /api/v1/reward-requests/:id',
    LIST: 'GET /api/v1/reward-requests',
  },
} as const;

export const ENDPOINT_PERMISSIONS = {
  [ENDPOINTS.AUTH.REGISTER]: [],
  [ENDPOINTS.AUTH.LOGIN]: [],
  [ENDPOINTS.AUTH.REFRESH]: [],
  [ENDPOINTS.AUTH.LOGOUT]: [ROLES.USER, ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],

  [ENDPOINTS.EVENTS.CREATE]: [ROLES.ADMIN, ROLES.OPERATOR],
  [ENDPOINTS.EVENTS.LIST]: [ROLES.USER, ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],
  [ENDPOINTS.EVENTS.DETAIL]: [ROLES.USER, ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],

  [ENDPOINTS.REWARDS.CREATE]: [ROLES.ADMIN, ROLES.OPERATOR],
  [ENDPOINTS.REWARDS.DETAIL]: [ROLES.USER, ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],

  [ENDPOINTS.REWARD_REQUESTS.CREATE]: [ROLES.USER, ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],
  [ENDPOINTS.REWARD_REQUESTS.DETAIL]: [ROLES.USER, ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],
  [ENDPOINTS.REWARD_REQUESTS.LIST]: [ROLES.ADMIN, ROLES.OPERATOR, ROLES.AUDITOR],
} as const;
